### ISSUE TITLE
admin-panel: change port for admin panel access

### ISSUE THREAD

**Issue by mpede** [Ballsdex-Team/BallsDex-DiscordBot#107]
Hi there,
your work and this bot are much appreciated. I am self-hosting this code, hopefully this feedback helps. I shall open a number of issues - please close/manage at your convenience.

if you want to serve the admin panel on a different port than 8000 you can add a ```--port XXXX``` to the poetry command in the docker-compose.yml under the admin-panel service app: 
(please note in the below example I removed the networks as it's using traefik as a router)

```
version: '3.4'

x-common-env-vars:
  - &postgres-db
    POSTGRES_DB=ballsdex
  - &postgres-user
    POSTGRES_USER=ballsdex
  - &postgres-url
    "BALLSDEXBOT_DB_URL=postgres://ballsdex:${POSTGRES_PASSWORD}@postgres:5432/ballsdex"

services:

  bot:
    restart: "no"
    image: ballsdex
    build: .
    environment:
      - *postgres-url
    depends_on:
      - postgres-db
    volumes:
      - type: bind
        source: ./
        target: /code
    tty: true
    command: poetry run python3 -m ballsdex --dev

  admin-panel:
    image: ballsdex
    expose:
      - 8111
    environment:
      - *postgres-url
      - "BALLSDEXBOT_REDIS_URL=redis://redis"
    depends_on:
      - postgres-db
      - redis-cache
    volumes:
      - type: bind
        source: ./
        target: /code
    tty: true
    command: poetry run uvicorn ballsdex.core.admin:_app --host 0.0.0.0 --port 8111
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mbda.rule=Host(`ballsadmin.someexample-replaced.com`)"
      - "traefik.http.routers.mbda.entrypoints=websecure"
      - "traefik.http.routers.mbda.tls.certresolver=mpede"
      - "traefik.http.routers.mbda.service=mbda"
      - "traefik.http.services.mbda.loadbalancer.server.port=8111"

  postgres-db:
    image: postgres
    restart: always
    hostname: postgres
    environment:
      - *postgres-db
      - *postgres-user
      - POSTGRES_PASSWORD
    volumes:  # Persist the db data
      - database-data:/var/lib/postgresql/data

  postgres-backup:
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres
    volumes:
      - /var/opt/pgbackups:/backups
    depends_on:
      - postgres-db
    environment:
      - *postgres-db
      - *postgres-user
      - POSTGRES_PASSWORD
      - POSTGRES_HOST=postgres
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=3928

  redis-cache:
    image: redis:latest
    restart: always
    hostname: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache-data:/data

volumes:
  database-data:
  cache-data:

networks:
  default:
    name: traefik
    external: true
```
